name: Publish Docker image

on:
  push:
    tags:
      - 'v*' 

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker tag variables
        id: vars
        run: |
          echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
          echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }} .
          docker tag ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }} ${{ steps.vars.outputs.image }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}
          docker push ${{ steps.vars.outputs.image }}:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: Release ${{ steps.vars.outputs.tag }}
          body: |
            📦 Docker image: `ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
